# Generated by Django 3.0.8 on 2020-07-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='username',
        ),
        migrations.AddField(
            model_name='item',
            name='userId',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
